apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: testpythonapps
spec:
  type: bindings.kafka
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: dapr-kafka.kafka:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: test
  - name: consumerGroup
    value: group1
  # publisher configuration: topic
  - name: publishTopic
    value: test
  - name: authRequired
    value: "false"
